Config.IgnoreClasses = {
    [13] = true, -- Bicicletas
    [14] = true, -- Barcos
    [15] = true, -- Helicópteros
    [16] = true, -- Aviões
    [21] = true, -- Comboios
}

Config.WheelBones = {
    [0] = 'wheel_lf',
    [1] = 'wheel_rf',
    [2] = 'wheel_lm',
    [3] = 'wheel_rm',
    [4] = 'wheel_lr',
    [5] = 'wheel_rr',
}

Config.HornLabels = {
    [0] = 'Buzina de Camião',
    [1] = 'Buzina de Polícia',
    [2] = 'Buzina de Palhaço',
    [3] = 'Buzina Musical 1',
    [4] = 'Buzina Musical 2',
    [5] = 'Buzina Musical 3',
    [6] = 'Buzina Musical 4',
    [7] = 'Buzina Musical 5',
    [8] = 'Trombone Triste',
    [9] = 'Clássica 1',
    [10] = 'Clássica 2',
    [11] = 'Clássica 3',
    [12] = 'Clássica 4',
    [13] = 'Clássica 5',
    [14] = 'Clássica 6',
    [15] = 'Clássica 7',
    [16] = 'Escala - Dó',
    [17] = 'Escala - Ré',
    [18] = 'Escala - Mi',
    [19] = 'Escala - Fá',
    [20] = 'Escala - Sol',
    [21] = 'Escala - Lá',
    [22] = 'Escala - Si',
    [23] = 'Escala - Dó (Alto)',
    [24] = 'Buzina Jazz 1',
    [25] = 'Buzina Jazz 2',
    [26] = 'Buzina Jazz 3',
    [27] = 'Jazz Loop',
    [28] = 'Hino Americano 1',
    [29] = 'Hino Americano 2',
    [30] = 'Hino Americano 3',
    [31] = 'Hino Americano 4',
    [32] = 'Clássica 8 Loop',
    [33] = 'Clássica 9 Loop',
    [34] = 'Clássica 10 Loop',
    [35] = 'Clássica 8',
    [36] = 'Clássica 9',
    [37] = 'Clássica 10',
    [38] = 'Funeral Loop',
    [39] = 'Funeral',
    [40] = 'Assustadora Loop',
    [41] = 'Assustadora',
    [42] = 'San Andreas Loop',
    [43] = 'San Andreas',
    [44] = 'Liberty City Loop',
    [45] = 'Liberty City',
    [46] = 'Festiva 1 Loop',
    [47] = 'Festiva 1',
    [48] = 'Festiva 2 Loop',
    [49] = 'Festiva 2',
    [50] = 'Festiva 3 Loop',
    [51] = 'Festiva 3'
}

-- Categorias de Rodas
Config.WheelCategories = {
    { label = 'Desportivas',        id = 0 },
    { label = 'Muscle',             id = 1 },
    { label = 'Lowrider',           id = 2 },
    { label = 'SUV',                id = 3 },
    { label = 'Todo-o-Terreno',     id = 4 },
    { label = 'Tuner',              id = 5 },
    { label = 'Motas',              id = 6 },
    { label = 'Luxo (High End)',    id = 7 },
    { label = 'Benny\'s Originais', id = 8 },
    { label = 'Benny\'s Bespoke',   id = 9 },
    { label = 'Fórmula 1',          id = 10 },
    { label = 'Street',             id = 11 },
    { label = 'Pista',              id = 12 },
}

-- Categorias de Interior
Config.InteriorCategories = {
    { label = 'Santantónio',        id = 5 },
    { label = 'Buzinas',            id = 14 },
    { label = 'Subwoofer',          id = 19 },
    { label = 'Tablier',            id = 29 },
    { label = 'Quadrantes',         id = 30 },
    { label = 'Colunas das Portas', id = 31 },
    { label = 'Bancos',             id = 32 },
    { label = 'Volante',            id = 33 },
    { label = 'Manete Mudanças',    id = 34 },
    { label = 'Placa Decorativa',   id = 35 },
    { label = 'Colunas Traseiras',  id = 36 },
}

-- Categorias de Exterior
Config.ExteriorCategories = {
    { label = 'Aileron',           id = 0 },
    { label = 'P. Choques Frontal',id = 1 },
    { label = 'P. Choques Trás',   id = 2 },
    { label = 'Saias Laterais',    id = 3 },
    { label = 'Escape',            id = 4 },
    { label = 'Grelha',            id = 6 },
    { label = 'Capô',              id = 7 },
    { label = 'Guarda-lamas Esq',  id = 8 },
    { label = 'Guarda-lamas Dir',  id = 9 },
    { label = 'Tejadilho',         id = 10 },
    { label = 'Hidráulicas',       id = 21 },
    { label = 'Faróis',            id = 22 },
    { label = 'Fumo dos Pneus',    id = 20 },
    { label = 'Rodas Traseiras',   id = 24 }, -- Para motas
    { label = 'Suporte Matrícula', id = 25 },
    { label = 'Matrícula Decor',   id = 26 },
    { label = 'Acabamento A',      id = 27 },
    { label = 'Ornamentos',        id = 28 },
    { label = 'Mala',              id = 37 },
    { label = 'Hidráulico (Mala)', id = 38 },
    { label = 'Bloco do Motor',    id = 39 },
    { label = 'Filtro de Ar',      id = 40 },
    { label = 'Barra Estabilizadora', id = 41 },
    { label = 'Cobertura Cava',    id = 42 },
    { label = 'Antena',            id = 43 },
    { label = 'Acabamento B',      id = 44 },
    { label = 'Depósito',          id = 45 },
    { label = 'Janelas',           id = 46 },
    { label = 'Portas',            id = 47 },
    { label = 'Autocolantes (Livery)', id = 48 },
    { label = 'Luzes de Teto',     id = 49 }, -- Lightbar
    { label = 'Pintura',           id = 50 }
}

-- Cores Xénon
Config.Xenon = {
    { label = 'Padrão',        id = -1 },
    { label = 'Branco',        id = 0 },
    { label = 'Azul',          id = 1 },
    { label = 'Azul Elétrico', id = 2 },
    { label = 'Verde Menta',   id = 3 },
    { label = 'Verde Lima',    id = 4 },
    { label = 'Amarelo',       id = 5 },
    { label = 'Dourado',       id = 6 },
    { label = 'Laranja',       id = 7 },
    { label = 'Vermelho',      id = 8 },
    { label = 'Rosa Pónei',    id = 9 },
    { label = 'Rosa Choque',   id = 10 },
    { label = 'Roxo',          id = 11 },
    { label = 'Luz Negra',     id = 12 },
}

-- Películas (Vidros)
Config.WindowTints = {
    { label = 'Nenhuma',       id = 0 },
    { label = 'Preto Puro',    id = 1 },
    { label = 'Fumado Escuro', id = 2 },
    { label = 'Fumado Claro',  id = 3 },
    { label = 'Original',      id = 4 },
    { label = 'Limusine',      id = 5 },
    { label = 'Verde',         id = 6 },
}

-- Matrículas
Config.PlateIndexes = {
    { label = 'Azul em Branco 1', id = 0 },
    { label = 'Amarelo em Preto', id = 1 },
    { label = 'Amarelo em Azul',  id = 2 },
    { label = 'Azul em Branco 2', id = 3 },
    { label = 'Azul em Branco 3', id = 4 },
    { label = 'Yankton',          id = 5 },
    { label = 'Ecola',            id = 6 },
    { label = 'Las Venturas',     id = 7 },
    { label = 'Liberty City',     id = 8 },
    { label = 'LS Car Meet',      id = 9 },
    { label = 'Panic',            id = 10 },
    { label = 'Pounders',         id = 11 },
    { label = 'Sprunk',           id = 12 },
}

-- Posição Neons
Config.Neon = {
    { label = 'Esquerda', id = 0 },
    { label = 'Direita',  id = 1 },
    { label = 'Frente',   id = 2 },
    { label = 'Trás',     id = 3 },
}

-- Cores Neons
Config.NeonColors = {
    { label = 'Branco',        r = 222, g = 222, b = 255 },
    { label = 'Azul',          r = 2,   g = 21,  b = 255 },
    { label = 'Azul Elétrico', r = 3,   g = 83,  b = 255 },
    { label = 'Verde Menta',   r = 0,   g = 255, b = 140 },
    { label = 'Verde Lima',    r = 94,  g = 255, b = 1 },
    { label = 'Amarelo',       r = 255, g = 255, b = 0 },
    { label = 'Dourado',       r = 255, g = 150, b = 0 },
    { label = 'Laranja',       r = 255, g = 62,  b = 0 },
    { label = 'Vermelho',      r = 255, g = 1,   b = 1 },
    { label = 'Rosa Pónei',    r = 255, g = 50,  b = 100 },
    { label = 'Rosa Choque',   r = 255, g = 5,   b = 190 },
    { label = 'Roxo',          r = 35,  g = 1,   b = 255 },
    { label = 'Luz Negra',     r = 15,  g = 3,   b = 255 },
}

-- Fumo dos Pneus
Config.TyreSmoke = {
    { label = 'Fumo Branco',   r = 254, g = 254, b = 254 },
    { label = 'Fumo Preto',    r = 1,   g = 1,   b = 1 },
    { label = 'Fumo Azul',     r = 0,   g = 150, b = 255 },
    { label = 'Fumo Amarelo',  r = 255, g = 255, b = 50 },
    { label = 'Fumo Laranja',  r = 255, g = 153, b = 51 },
    { label = 'Fumo Vermelho', r = 255, g = 10,  b = 10 },
    { label = 'Fumo Verde',    r = 10,  g = 255, b = 10 },
    { label = 'Fumo Roxo',     r = 153, g = 10,  b = 153 },
    { label = 'Fumo Rosa',     r = 255, g = 102, b = 178 },
    { label = 'Fumo Cinzento', r = 128, g = 128, b = 128 }
}

-- CORES DE PINTURA (TRADUZIDAS PT-PT)
Config.Paints = {

    Metallic = { -- Metálicas
        { label = 'Preto Metálico',               id = 0,   hex = '0d1116' },
        { label = 'Preto Grafite Metálico',       id = 1,   hex = '1c1d21' },
        { label = 'Aço Preto Metálico',           id = 2,   hex = '32383d' },
        { label = 'Prata Escuro Metálico',        id = 3,   hex = '454b4f' },
        { label = 'Prata Metálico',               id = 4,   hex = '999da0' },
        { label = 'Prata Azulado Metálico',       id = 5,   hex = 'c2c4c6' },
        { label = 'Cinzento Aço Metálico',        id = 6,   hex = '979a97' },
        { label = 'Prata Sombra Metálico',        id = 7,   hex = '637380' },
        { label = 'Prata Pedra Metálico',         id = 8,   hex = '63625c' },
        { label = 'Prata Meia-Noite Metálico',    id = 9,   hex = '3c3f47' },
        { label = 'Metal Armas Metálico',         id = 10,  hex = '444e54' },
        { label = 'Cinzento Antracite Metálico',  id = 11,  hex = '1d2129' },
        { label = 'Vermelho Metálico',            id = 27,  hex = 'c00e1a' },
        { label = 'Vermelho Torino Metálico',     id = 28,  hex = 'da1918' },
        { label = 'Vermelho Fórmula Metálico',    id = 29,  hex = 'b6111b' },
        { label = 'Vermelho Blaze Metálico',      id = 30,  hex = 'a51e23' },
        { label = 'Vermelho Graceful Metálico',   id = 31,  hex = '7b1a22' },
        { label = 'Vermelho Garnet Metálico',     id = 32,  hex = '8e1b1f' },
        { label = 'Vermelho Deserto Metálico',    id = 33,  hex = '6f1818' },
        { label = 'Vermelho Cabernet Metálico',   id = 34,  hex = '49111d' },
        { label = 'Vermelho Doce Metálico',       id = 35,  hex = 'b60f25' },
        { label = 'Laranja Nascer do Sol Metálico',id = 36, hex = 'd44a17' },
        { label = 'Dourado Clássico Metálico',    id = 37,  hex = 'c2944f' },
        { label = 'Laranja Metálico',             id = 38,  hex = 'f78616' },
        { label = 'Verde Escuro Metálico',        id = 49,  hex = '132428' },
        { label = 'Verde Racing Metálico',        id = 50,  hex = '122e2b' },
        { label = 'Verde Mar Metálico',           id = 51,  hex = '12383c' },
        { label = 'Verde Azeitona Metálico',      id = 52,  hex = '31423f' },
        { label = 'Verde Metálico',               id = 53,  hex = '155c2d' },
        { label = 'Azul Petróleo Metálico',       id = 54,  hex = '1b6770' },
        { label = 'Azul Meia-Noite Metálico',     id = 61,  hex = '222e46' },
        { label = 'Azul Escuro Metálico',         id = 62,  hex = '233155' },
        { label = 'Azul Saxónia Metálico',        id = 63,  hex = '304c7e' },
        { label = 'Azul Metálico',                id = 64,  hex = '47578f' },
        { label = 'Azul Marinho Metálico',        id = 65,  hex = '637ba7' },
        { label = 'Azul Porto Metálico',          id = 66,  hex = '394762' },
        { label = 'Azul Diamante Metálico',       id = 67,  hex = 'd6e7f1' },
        { label = 'Azul Surf Metálico',           id = 68,  hex = '76afbe' },
        { label = 'Azul Náutico Metálico',        id = 69,  hex = '345e72' },
        { label = 'Azul Brilhante Metálico',      id = 70,  hex = '0b9cf1' },
        { label = 'Azul Roxo Metálico',           id = 71,  hex = '2f2d52' },
        { label = 'Azul Spinnaker Metálico',      id = 72,  hex = '282c4d' },
        { label = 'Azul Ultra Metálico',          id = 73,  hex = '2354a1' },
        { label = 'Azul Claro Metálico',          id = 74,  hex = '6ea3c6' },
        { label = 'Amarelo Táxi Metálico',        id = 88,  hex = 'ffcf20' },
        { label = 'Amarelo Corrida Metálico',     id = 89,  hex = 'fbe212' },
        { label = 'Bronze Metálico',              id = 90,  hex = '916532' },
        { label = 'Amarelo Pássaro Metálico',     id = 91,  hex = 'e0e13d' },
        { label = 'Lima Metálico',                id = 92,  hex = '98d223' },
        { label = 'Champanhe Metálico',           id = 93,  hex = '9b8c78' },
        { label = 'Bege Pueblo Metálico',         id = 94,  hex = '503218' },
        { label = 'Marfim Escuro Metálico',       id = 95,  hex = '473f2b' },
        { label = 'Castanho Choco Metálico',      id = 96,  hex = '221b19' },
        { label = 'Castanho Dourado Metálico',    id = 97,  hex = '653f23' },
        { label = 'Castanho Claro Metálico',      id = 98,  hex = '775c3e' },
        { label = 'Bege Palha Metálico',          id = 99,  hex = 'ac9975' },
        { label = 'Castanho Musgo Metálico',      id = 100, hex = '6c6b4b' },
        { label = 'Castanho Biston Metálico',     id = 101, hex = '402e2b' },
        { label = 'Madeira de Faia Metálico',     id = 102, hex = 'a4965f' },
        { label = 'Faia Escura Metálico',         id = 103, hex = '46231a' },
        { label = 'Laranja Choco Metálico',       id = 104, hex = '752b19' },
        { label = 'Areia da Praia Metálico',      id = 105, hex = 'bfae7b' },
        { label = 'Areia Branqueada Metálico',    id = 106, hex = 'dfd5b2' },
        { label = 'Creme Metálico',               id = 107, hex = 'f7edd5' },
        { label = 'Branco Metálico',              id = 111, hex = 'fffff6' },
        { label = 'Branco Gelo Metálico',         id = 112, hex = 'eaeaea' },
        { label = 'Verde Securicor Metálico',     id = 125, hex = '83c566' },
        { label = 'Rosa Vermilion Metálico',      id = 137, hex = 'df5891' },
        { label = 'Azul Preto Metálico',          id = 141, hex = '0a0c17' },
        { label = 'Roxo Preto Metálico',          id = 142, hex = '0c0d18' },
        { label = 'Vermelho Preto Metálico',      id = 143, hex = '0e0d14' },
        { label = 'Roxo Metálico',                id = 145, hex = '621276' },
        { label = 'Azul V Escuro Metálico',       id = 146, hex = '0b1421' },
        { label = 'Vermelho Lava Metálico',       id = 150, hex = 'bc1917' },
    },

    Matte = { -- Mate (Fosco)
        { label = 'Preto Mate',           id = 12,  hex = '13181f' },
        { label = 'Cinzento Mate',        id = 13,  hex = '26282a' },
        { label = 'Cinzento Claro Mate',  id = 14,  hex = '515554' },
        { label = 'Vermelho Mate',        id = 39,  hex = 'cf1f21' },
        { label = 'Vermelho Escuro Mate', id = 40,  hex = '732021' },
        { label = 'Laranja Mate',         id = 41,  hex = 'f27d20' },
        { label = 'Amarelo Mate',         id = 42,  hex = 'ffc91f' },
        { label = 'Verde Lima Mate',      id = 55,  hex = '66b81f' },
        { label = 'Azul Escuro Mate',     id = 82,  hex = '1f2852' },
        { label = 'Azul Mate',            id = 83,  hex = '253aa7' },
        { label = 'Azul Meia-Noite Mate', id = 84,  hex = '1c3551' },
        { label = 'Verde Mate',           id = 128, hex = '4e6443' },
        { label = 'Castanho Mate',        id = 129, hex = 'bcac8f' },
        { label = 'Branco Mate',          id = 131, hex = 'fcf9f1' },
        { label = 'Roxo Mate',            id = 148, hex = '6b1f7b' },
        { label = 'Roxo Escuro Mate',     id = 149, hex = '1e1d22' },
        { label = 'Verde Floresta Mate',  id = 151, hex = '2d362a' },
        { label = 'Verde Azeitona Mate',  id = 152, hex = '696748' },
        { label = 'Castanho Deserto Mate',id = 153, hex = '7a6c55' },
        { label = 'Bronzeado Deserto Mate',id = 154, hex = 'c3b492' },
        { label = 'Verde Folhagem Mate',  id = 155, hex = '5a6352' },
    },

    Util = { -- Utilitário (Sólido)
        { label = 'Preto Util',           id = 15,  hex = '151921' },
        { label = 'Preto Poly Util',      id = 16,  hex = '1e2429' },
        { label = 'Prata Escuro Util',    id = 17,  hex = '333a3c' },
        { label = 'Prata Util',           id = 18,  hex = '8c9095' },
        { label = 'Metal Armas Util',     id = 19,  hex = '39434d' },
        { label = 'Prata Sombra Util',    id = 20,  hex = '506272' },
        { label = 'Vermelho Util',        id = 43,  hex = '9c1016' },
        { label = 'Vermelho Brilhante Util', id = 44,  hex = 'de0f18' },
        { label = 'Vermelho Garnet Util', id = 45,  hex = '8f1e17' },
        { label = 'Verde Escuro Util',    id = 56,  hex = '22383e' },
        { label = 'Verde Util',           id = 57,  hex = '1d5a3f' },
        { label = 'Azul Escuro Util',     id = 75,  hex = '112552' },
        { label = 'Azul Meia-Noite Util', id = 76,  hex = '1b203e' },
        { label = 'Azul Util',            id = 77,  hex = '275190' },
        { label = 'Azul Espuma do Mar Util', id = 78,  hex = '608592' },
        { label = 'Azul Relâmpago Util',  id = 79,  hex = '2446a8' },
        { label = 'Azul Maui Poly Util',  id = 80,  hex = '4271e1' },
        { label = 'Azul Brilhante Util',  id = 81,  hex = '3b39e0' },
        { label = 'Castanho Util',        id = 108, hex = '3a2a1b' },
        { label = 'Castanho Médio Util',  id = 109, hex = '785f33' },
        { label = 'Castanho Claro Util',  id = 110, hex = 'b5a079' },
        { label = 'Branco Sujo Util',     id = 122, hex = 'dfddd0' },
    },

    Worn = { -- Desgastado
        { label = 'Preto Desgastado',       id = 21,  hex = '1e232f' },
        { label = 'Grafite Desgastado',     id = 22,  hex = '363a3f' },
        { label = 'Cinzento Prata Desgastado', id = 23,  hex = 'a0a199' },
        { label = 'Prata Desgastado',       id = 24,  hex = 'd3d3d3' },
        { label = 'Azul Prata Desgastado',  id = 25,  hex = 'b7bfca' },
        { label = 'Prata Sombra Desgastado', id = 26,  hex = '778794' },
        { label = 'Vermelho Desgastado',    id = 46,  hex = 'a94744' },
        { label = 'Vermelho Dourado Desgastado', id = 47,  hex = 'b16c51' },
        { label = 'Vermelho Escuro Desgastado', id = 48,  hex = '371c25' },
        { label = 'Verde Escuro Desgastado', id = 58,  hex = '2d423f' },
        { label = 'Verde Desgastado',       id = 59,  hex = '45594b' },
        { label = 'Lavagem Mar Desgastado', id = 60,  hex = '65867f' },
        { label = 'Azul Escuro Desgastado', id = 85,  hex = '4c5f81' },
        { label = 'Azul Desgastado',        id = 86,  hex = '58688e' },
        { label = 'Azul Claro Desgastado',  id = 87,  hex = '74b5d8' },
        { label = 'Bege Mel Desgastado',    id = 113, hex = 'b0ab94' },
        { label = 'Castanho Desgastado',    id = 114, hex = '453831' },
        { label = 'Castanho Escuro Desgastado', id = 115, hex = '2a282b' },
        { label = 'Bege Palha Desgastado',  id = 116, hex = '726c57' },
        { label = 'Branco Sujo Desgastado', id = 121, hex = 'eae6de' },
        { label = 'Laranja Desgastado',     id = 123, hex = 'f2ad2e' },
        { label = 'Laranja Claro Desgastado', id = 124, hex = 'f9a458' },
        { label = 'Amarelo Táxi Desgastado', id = 126, hex = 'f1cc40' },
        { label = 'Laranja Desgastado 2',   id = 130, hex = 'f8b658' },
        { label = 'Branco Desgastado',      id = 132, hex = 'fffffb' },
        { label = 'Verde Azeitona Desgastado', id = 133, hex = '81844c' },
    },

    Misc = { -- Metais e Cromados
        { label = 'Aço Escovado',       id = 117, hex = '6a747c' },
        { label = 'Aço Preto Escovado', id = 118, hex = '354158' },
        { label = 'Alumínio Escovado',  id = 119, hex = '9ba0a8' },
        { label = 'Cromado',            id = 120, hex = '5870a1' },
        { label = 'Azul Polícia',       id = 127, hex = '4cc3da' },
        { label = 'Branco Puro',        id = 134, hex = 'ffffff' },
        { label = 'Rosa Choque',        id = 135, hex = 'f21f99' },
        { label = 'Rosa Salmão',        id = 136, hex = 'fdd6cd' },
        { label = 'Laranja',            id = 138, hex = 'f6ae20' },
        { label = 'Verde',              id = 139, hex = 'b0ee6e' },
        { label = 'Azul',               id = 140, hex = '08e9fa' },
        { label = 'Verde Caçador',      id = 144, hex = '9f9e8a' },
        { label = 'Preto Mod Shop',     id = 147, hex = '11141a' },
        { label = 'Liga Metálica',      id = 156, hex = '81827f' },
        { label = 'Azul Epsilon',       id = 157, hex = 'afd6e4' },
        { label = 'Ouro Puro',          id = 158, hex = '7a6440' },
        { label = 'Ouro Escovado',      id = 159, hex = '7f6a48' }
    },

    Chameleon = { -- Camaleão
        { label = 'Vermelho Anodizado',           id = 161, hex = 'CF1020' },
        { label = 'Vinho Anodizado',              id = 162, hex = '5E1224' },
        { label = 'Roxo Anodizado',               id = 163, hex = '800080' },
        { label = 'Azul Anodizado',               id = 164, hex = '0000FF' },
        { label = 'Verde Anodizado',              id = 165, hex = '008000' },
        { label = 'Lima Anodizado',               id = 166, hex = 'AFFF00' },
        { label = 'Cobre Anodizado',              id = 167, hex = 'B87333' },
        { label = 'Bronze Anodizado',             id = 168, hex = 'CD7F32' },
        { label = 'Champanhe Anodizado',          id = 169, hex = 'F7E7CE' },
        { label = 'Ouro Anodizado',               id = 170, hex = 'FFD700' },
        { label = 'Flip Verde Azul',              id = 171, hex = '1164B4' },
        { label = 'Flip Verde Vermelho',          id = 172, hex = 'B43104' },
        { label = 'Flip Verde Castanho',          id = 173, hex = '735C12' },
        { label = 'Flip Verde Turquesa',          id = 174, hex = '43C6DB' },
        { label = 'Flip Verde Roxo',              id = 175, hex = '9D00FF' },
        { label = 'Flip Petróleo Roxo',           id = 176, hex = '6A0DAD' },
        { label = 'Flip Turquesa Vermelho',       id = 177, hex = 'E60026' },
        { label = 'Flip Turquesa Roxo',           id = 178, hex = '30D5C8' },
        { label = 'Flip Ciano Roxo',              id = 179, hex = '0FF0FC' },
        { label = 'Flip Azul Rosa',               id = 180, hex = '4C2882' },
        { label = 'Flip Azul Verde',              id = 181, hex = '138808' },
        { label = 'Flip Roxo Vermelho',           id = 182, hex = '9B111E' },
        { label = 'Flip Roxo Verde',              id = 183, hex = '6B2E53' },
        { label = 'Flip Magenta Verde',           id = 184, hex = 'CA1F7B' },
        { label = 'Flip Magenta Amarelo',         id = 185, hex = 'FEDF00' },
        { label = 'Flip Borgonha Verde',          id = 186, hex = '900020' },
        { label = 'Flip Magenta Ciano',           id = 187, hex = '00FFA1' },
        { label = 'Flip Cobre Roxo',              id = 188, hex = 'B87333' },
        { label = 'Flip Magenta Laranja',         id = 189, hex = 'FF5F1F' },
        { label = 'Flip Vermelho Laranja',        id = 190, hex = 'FF4500' },
        { label = 'Flip Laranja Roxo',            id = 191, hex = 'B04080' },
        { label = 'Flip Laranja Azul',            id = 192, hex = '0047AB' },
        { label = 'Flip Branco Roxo',             id = 193, hex = 'F8F0E3' },
        { label = 'Flip Arco-íris Vermelho',      id = 194, hex = 'ED2939' },
        { label = 'Flip Arco-íris Azul',          id = 195, hex = '4B0082' },
        { label = 'Pérola Verde Escuro',          id = 196, hex = '013220' },
        { label = 'Pérola Petróleo Escuro',       id = 197, hex = '008080' },
        { label = 'Pérola Azul Escuro',           id = 198, hex = '000080' },
        { label = 'Pérola Roxo Escuro',           id = 199, hex = '301934' },
        { label = 'Pérola Mancha de Óleo',        id = 200, hex = '4B0082' },
        { label = 'Pérola Verde Claro',           id = 201, hex = '99E550' },
        { label = 'Pérola Azul Claro',            id = 202, hex = 'ADD8E6' },
        { label = 'Pérola Roxo Claro',            id = 203, hex = '967BB6' },
        { label = 'Pérola Rosa Claro',            id = 203, hex = 'FFB6C1' },
        { label = 'Pérola Branco Sujo',           id = 204, hex = 'F2F0E6' },
        { label = 'Pérola Rosa',                  id = 205, hex = 'EAADEA' },
        { label = 'Pérola Amarelo',               id = 206, hex = 'FFF000' },
        { label = 'Pérola Verde',                 id = 207, hex = '00A550' },
        { label = 'Pérola Azul',                  id = 208, hex = '0000FF' },
        { label = 'Pérola Creme',                 id = 209, hex = 'FFFDD0' },
        { label = 'Prismático Branco',            id = 210, hex = 'FFFFFF' },
        { label = 'Prismático Grafite',           id = 211, hex = '251607' },
        { label = 'Prismático Azul Escuro',       id = 212, hex = '00008B' },
        { label = 'Prismático Roxo Escuro',       id = 213, hex = '301934' },
        { label = 'Prismático Rosa Choque',       id = 214, hex = 'FF69B4' },
        { label = 'Prismático Vermelho Escuro',   id = 215, hex = '8B0000' },
        { label = 'Prismático Verde Escuro',      id = 216, hex = '013220' },
        { label = 'Prismático Preto',             id = 217, hex = '000000' },
        { label = 'Mancha Óleo Preto',            id = 218, hex = '121212' },
        { label = 'Arco-íris Preto',              id = 219, hex = '000000' },
        { label = 'Prismático',                   id = 220, hex = 'CCCCCC' },
        { label = 'Holográfico Preto',            id = 221, hex = '101010' },
        { label = 'Holográfico Branco',           id = 222, hex = 'E6E8FA' },
        { label = 'Monocromático',                id = 223, hex = 'B4B4B4' },
        { label = 'Noite & Dia',                  id = 224, hex = '333366' },
        { label = 'The Verlierer',                id = 225, hex = '550055' },
        { label = 'Sprunk Extremo',               id = 226, hex = '00FF00' },
        { label = 'Vice City',                    id = 227, hex = 'FF00FF' },
        { label = 'Synthwave Nights',             id = 228, hex = 'FF007F' },
        { label = 'Quatro Estações',              id = 229, hex = '73C2FB' },
        { label = 'Maisonette 9 Retro',           id = 230, hex = 'DCDCDC' },
        { label = 'Bubblegum',                    id = 231, hex = 'FFC0CB' },
        { label = 'Arco-íris Completo',           id = 232, hex = 'FF0000' },
        { label = 'Pôr do Sol',                   id = 233, hex = 'FFD700' },
        { label = 'Os Sete',                      id = 234, hex = '701C1C' },
        { label = 'Kamen Rider',                  id = 235, hex = '1C1C70' },
        { label = 'Aberração Cromática',          id = 236, hex = 'D8BFD8' },
        { label = "É Natal",                      id = 237, hex = 'FF0000' },
        { label = 'Temperatura',                  id = 238, hex = 'FFA07A' },
        { label = 'Pérola Amarelo Laranja',       id = 239, hex = 'FFAE42' },
        { label = 'Pérola Rosa Azul',             id = 240, hex = 'D8BFD8' },
        { label = 'Pérola Verde Azul',            id = 241, hex = '3CB371' },
        { label = 'Pérola Turquesa Preto',        id = 242, hex = '00CED1' }
    },
}

if Config.ColorFavorites then
    Config.Paints.Favorites = { -- Podes adicionar as tuas cores favoritas aqui por hex
        { label = 'Minha Cor Personalizada!', hex = '' }
    }
end